project_id = "htuearldqvzqohoxwmdp"

[functions.tspoonlab-health]
verify_jwt = false

[functions.telegram-system-alerts]
verify_jwt = false

[functions.tspoonlab-sync-stock]
verify_jwt = false

[functions.tspoonlab-sync-productions]
verify_jwt = false

[functions.tspoonlab-sync-orders]
verify_jwt = false
